apiVersion: v1
kind: Service
metadata:
  name: observations-retriever
  labels:
    app: retriever
spec:
  ports:
    - name: service
      port: 4001
      protocol: TCP
      targetPort: 4001
  selector:
    app.retriever: workload
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: observations-retriever
  labels:
    app: retriever
    app.retriever: deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.retriever: workload
  template:
    metadata:
      labels:
        app: retriever
        app.retriever: workload
    spec:
      containers:
        - name: observations-retriever
          image: digitalgoetz/retriever:1.0.0
          imagePullPolicy: Always
          ports:
            - name: service
              containerPort: 4001
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
              cpu: 1000m
          env:
            - name: APP_POSTGRES_PASSWORD
              value: "password"
            - name: APP_POSTGRES_USER
              value: "postgres"
            - name: APP_POSTGRES_DB
              value: "observations"
            - name: APP_POSTGRES_HOST
              value: "database-postgresql.traffic"
